// Copyright 2026 The tss Authors.
//
// This generator invokes fiat-crypto from the fiat-crypto-go-tool Docker image
// and commits the generated Go source.

//go:build ignore

package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
)

const defaultToolImage = "ghcr.io/islishude/fiat-crypto-go-tool"

var curves = []struct {
	dir     string
	pkg     string
	desc    string
	modulus string
}{
	{
		dir:     "secp256k1field",
		pkg:     "secp256k1field",
		modulus: "2^256 - 2^32 - 977",
	},
	{
		dir:     "secp256k1scalar",
		pkg:     "secp256k1scalar",
		modulus: "2^256 - 432420386565659656852420866394968145599",
	},
	{
		dir:     "ed25519scalar",
		pkg:     "ed25519scalar",
		modulus: "2^252 + 27742317777372353535851937790883648493",
	},
}

func main() {
	for _, c := range curves {
		log.Printf("generating %s", c.dir)
		out := runFiat(c)
		out, err := format.Source(out)
		if err != nil {
			log.Fatal(err)
		}
		if err := os.MkdirAll(c.dir, 0755); err != nil {
			log.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(c.dir, c.dir+".go"), out, 0644); err != nil {
			log.Fatal(err)
		}
	}
}

func runFiat(c struct {
	dir     string
	pkg     string
	desc    string
	modulus string
}) []byte {
	args := []string{
		"word-by-word-montgomery",
		"--lang", "Go",
		"--no-wide-int",
		"--relax-primitive-carry-to-bitwidth", "32,64",
		"--cmovznz-by-mul",
		"--internal-static",
		"--package-case", "flatcase",
		"--public-function-case", "UpperCamelCase",
		"--private-function-case", "camelCase",
		"--public-type-case", "UpperCamelCase",
		"--private-type-case", "camelCase",
		"--no-prefix-fiat",
		"--doc-newline-in-typedef-bounds",
		"--doc-prepend-header", "Code generated by Fiat Cryptography. DO NOT EDIT.",
		"--doc-text-before-function-name", "",
		"--doc-text-before-type-name", "",
		"--package-name", c.pkg,
		c.desc,
		"64",
		c.modulus,
		"mul", "square", "add", "sub", "opp",
		"from_montgomery", "to_montgomery",
		"nonzero", "selectznz",
		"to_bytes", "from_bytes",
		"one", "msat", "divstep", "divstep_precomp",
	}
	cmd := fiatCryptoCommand(args...)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}
	out = bytes.ReplaceAll(out, []byte("”"), []byte("''"))
	return out
}

func fiatCryptoCommand(args ...string) *exec.Cmd {
	if bin := os.Getenv("FIAT_CRYPTO_BIN"); bin != "" {
		return exec.Command(bin, args...)
	}
	image := os.Getenv("FIAT_CRYPTO_GO_TOOL_IMAGE")
	if image == "" {
		image = defaultToolImage
	}
	all := []string{
		"run",
		"--rm",
		"--entrypoint", "fiat_crypto",
		image,
	}
	all = append(all, args...)
	return exec.Command("docker", all...)
}
