#!/bin/sh
set -eu

docker run --rm --entrypoint fiat_crypto ghcr.io/islishude/fiat-crypto-go-tool \
  word-by-word-montgomery --lang Go --no-wide-int \
  --relax-primitive-carry-to-bitwidth 32,64 --cmovznz-by-mul \
  --internal-static --package-case flatcase \
  --public-function-case UpperCamelCase --private-function-case camelCase \
  --public-type-case UpperCamelCase --private-type-case camelCase \
  --no-prefix-fiat --doc-newline-in-typedef-bounds \
  --doc-prepend-header 'Code generated by Fiat Cryptography. DO NOT EDIT.' \
  --doc-text-before-function-name '' --doc-text-before-type-name '' \
  --package-name secp256k1field '' 64 '2^256 - 2^32 - 977' \
  mul square add sub opp from_montgomery to_montgomery nonzero selectznz \
  to_bytes from_bytes one msat divstep divstep_precomp \
  > secp256k1field/secp256k1field.go

docker run --rm --entrypoint fiat_crypto ghcr.io/islishude/fiat-crypto-go-tool \
  word-by-word-montgomery --lang Go --no-wide-int \
  --relax-primitive-carry-to-bitwidth 32,64 --cmovznz-by-mul \
  --internal-static --package-case flatcase \
  --public-function-case UpperCamelCase --private-function-case camelCase \
  --public-type-case UpperCamelCase --private-type-case camelCase \
  --no-prefix-fiat --doc-newline-in-typedef-bounds \
  --doc-prepend-header 'Code generated by Fiat Cryptography. DO NOT EDIT.' \
  --doc-text-before-function-name '' --doc-text-before-type-name '' \
  --package-name secp256k1scalar '' 64 \
  '2^256 - 432420386565659656852420866394968145599' \
  mul square add sub opp from_montgomery to_montgomery nonzero selectznz \
  to_bytes from_bytes one msat divstep divstep_precomp \
  > secp256k1scalar/secp256k1scalar.go

docker run --rm --entrypoint fiat_crypto ghcr.io/islishude/fiat-crypto-go-tool \
  word-by-word-montgomery --lang Go --no-wide-int \
  --relax-primitive-carry-to-bitwidth 32,64 --cmovznz-by-mul \
  --internal-static --package-case flatcase \
  --public-function-case UpperCamelCase --private-function-case camelCase \
  --public-type-case UpperCamelCase --private-type-case camelCase \
  --no-prefix-fiat --doc-newline-in-typedef-bounds \
  --doc-prepend-header 'Code generated by Fiat Cryptography. DO NOT EDIT.' \
  --doc-text-before-function-name '' --doc-text-before-type-name '' \
  --package-name ed25519scalar '' 64 \
  '2^252 + 27742317777372353535851937790883648493' \
  mul square add sub opp from_montgomery to_montgomery nonzero selectznz \
  to_bytes from_bytes one msat divstep divstep_precomp \
  > ed25519scalar/ed25519scalar.go
