// Copyright 2026 The tss Authors.
//
// This generator invokes addchain from the fiat-crypto-go-tool Docker image
// to produce optimized addition-chain exponentiation for secp256k1 field and
// scalar inversion and square root.

//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const defaultToolImage = "ghcr.io/islishude/fiat-crypto-go-tool"

type target struct {
	Filename string
	Pkg      string
	Wrappers []wrapper
}

type wrapper struct {
	FuncName string
	Comment  string
	Expr     string
	ElemType string
	MulFunc  string
	SqrFunc  string
}

func main() {
	wd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	secpDir := filepath.Join(filepath.Dir(wd), "curve", "secp256k1")

	targets := []target{{
		Filename: filepath.Join(secpDir, "field_inv_gen.go"),
		Pkg:      "secp256k1",
		Wrappers: []wrapper{
			{
				FuncName: "fieldInvAddchain",
				Comment:  "fieldInvAddchain computes x^(P-2) mod P via an optimized addition chain.",
				Expr:     "2^256 - 2^32 - 977 - 2",
				ElemType: "FieldElement", MulFunc: "FieldMul", SqrFunc: "FieldSquare",
			},
			{
				FuncName: "fieldSqrtAddchain",
				Comment:  "fieldSqrtAddchain computes x^((P+1)/4) mod P via an optimized addition chain.",
				Expr:     "2^254 - 2^30 - 244",
				ElemType: "FieldElement", MulFunc: "FieldMul", SqrFunc: "FieldSquare",
			},
		},
	}, {
		Filename: filepath.Join(secpDir, "scalar_inv_gen.go"),
		Pkg:      "secp256k1",
		Wrappers: []wrapper{{
			FuncName: "scalarInvAddchain",
			Comment:  "scalarInvAddchain computes x^(N-2) mod N via an optimized addition chain.",
			Expr:     "2^256 - 432420386565659656852420866394968145599 - 2",
			ElemType: "Scalar", MulFunc: "ScalarMul", SqrFunc: "ScalarSquare",
		}},
	}}

	for _, t := range targets {
		var out bytes.Buffer
		out.WriteString("// Code generated by internal/fiat/generate_addchain.go. DO NOT EDIT.\n\n")
		out.WriteString("package ")
		out.WriteString(t.Pkg)
		out.WriteString("\n\n")
		for _, w := range t.Wrappers {
			out.WriteString(generateWrapper(w))
			out.WriteByte('\n')
		}
		formatted, err := format.Source(out.Bytes())
		if err != nil {
			log.Fatalf("format %s: %v", t.Filename, err)
		}
		if err := os.WriteFile(t.Filename, formatted, 0644); err != nil {
			log.Fatal(err)
		}
		log.Printf("wrote %s", t.Filename)
	}
}

func generateWrapper(w wrapper) string {
	acc := search(w.Expr)
	defer os.Remove(acc)

	tmpl, err := os.CreateTemp(".", "secp256k1-addchain-template-*.tmpl")
	if err != nil {
		log.Fatal(err)
	}
	defer os.Remove(tmpl.Name())
	if _, err := tmpl.WriteString(addchainTemplate(w)); err != nil {
		log.Fatal(err)
	}
	if err := tmpl.Close(); err != nil {
		log.Fatal(err)
	}

	return runAddchain("gen", "-tmpl", tmpl.Name(), acc)
}

func search(expr string) string {
	acc, err := os.CreateTemp(".", "secp256k1-addchain-*.acc")
	if err != nil {
		log.Fatal(err)
	}
	defer acc.Close()
	log.Printf("searching addition chain for %s", expr)
	out := runAddchain("search", expr)
	if _, err := acc.WriteString(out); err != nil {
		log.Fatal(err)
	}
	return acc.Name()
}

func runAddchain(args ...string) string {
	cmd := addchainCommand(args...)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		log.Fatalf("addchain: %v", err)
	}
	return string(out)
}

func addchainCommand(args ...string) *exec.Cmd {
	if bin := os.Getenv("ADDCHAIN_BIN"); bin != "" {
		return exec.Command(bin, args...)
	}
	image := os.Getenv("FIAT_CRYPTO_GO_TOOL_IMAGE")
	if image == "" {
		image = defaultToolImage
	}
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	all := []string{
		"run",
		"--rm",
		"--entrypoint", "addchain",
		"-v", fmt.Sprintf("%s:/work", cwd),
		"-w", "/work",
		image,
	}
	all = append(all, args...)
	return exec.Command("docker", all...)
}

func addchainTemplate(w wrapper) string {
	return strings.NewReplacer(
		"FUNC_NAME", w.FuncName,
		"COMMENT", w.Comment,
		"ELEM_TYPE", w.ElemType,
		"MUL_FUNC", w.MulFunc,
		"SQR_FUNC", w.SqrFunc,
	).Replace(`// COMMENT
// Addition chain:
//
{{- range lines (format .Script) }}
//    {{ . }}
{{- end }}
func FUNC_NAME(x ELEM_TYPE) ELEM_TYPE {
	var z ELEM_TYPE
	var (
		{{- range .Program.Temporaries }}
		{{ . }} ELEM_TYPE
		{{- end }}
	)

	{{ range $i := .Program.Instructions }}
	{{- with add $i.Op }}
	{{ $i.Output }} = MUL_FUNC({{ .X }}, {{ .Y }})
	{{ end -}}

	{{- with double $i.Op }}
	{{ $i.Output }} = SQR_FUNC({{ .X }})
	{{ end -}}

	{{- with shift $i.Op -}}
	{{- if ne $i.Output.Identifier .X.Identifier }}
	{{ $i.Output }} = SQR_FUNC({{ .X }})
	for s := 1; s < {{ .S }}; s++ {
		{{ $i.Output }} = SQR_FUNC({{ $i.Output }})
	}
	{{- else }}
	for range {{ .S }} {
		{{ $i.Output }} = SQR_FUNC({{ $i.Output }})
	}
	{{- end }}
	{{ end -}}
	{{- end }}
	return z
}
`)
}
