package secp256k1

import (
	"errors"
	"sync/atomic"
)

// Presign consumption lifecycle:
//
//  1. A Presign is generated by a PresignSession and MUST be persisted by the
//     caller immediately after the session completes.
//  2. StartSign atomically claims the presign locally before any outbound
//     signing envelope is constructed. Shallow copies of a generated presign
//     share this local claim state.
//  3. StartSign then calls [PresignStore.ClaimPresign] before any outbound
//     signing envelope is constructed. Production signing requires this durable
//     store so a presign ID cannot be reused across processes or restarts.
//  4. MarshalBinary writes the local claim as a wire-format consumed snapshot.
//     The local claim and durable store are the security boundary.
//  5. If the signing session fails after StartSign but the caller is
//     uncertain whether a partial signature was emitted, the presign MUST be
//     discarded rather than reused.

func newPresignConsumedState(consumed bool) *atomic.Bool {
	state := new(atomic.Bool)
	state.Store(consumed)
	return state
}

// MarkPresignConsumed marks p's local claim consumed.
// It is not a substitute for [PresignStore].
func MarkPresignConsumed(p *Presign) error {
	if p == nil {
		return errors.New("nil presign")
	}
	if p.consumed == nil {
		return errors.New("presign claim state unavailable")
	}
	p.consumed.Store(true)
	return nil
}

// IsPresignConsumed reports whether the presign has been consumed.
func IsPresignConsumed(p *Presign) bool {
	return p == nil || p.consumed == nil || p.consumed.Load()
}

func claimPresignForSigning(presign *Presign) bool {
	// Mark consumed before constructing the outbound sign envelope so accidental
	// reuse fails before any new partial signature can leave the process.
	return presign != nil &&
		presign.consumed != nil &&
		presign.consumed.CompareAndSwap(false, true)
}

func rollbackPresignClaim(presign *Presign) {
	if presign != nil && presign.consumed != nil {
		presign.consumed.Store(false)
	}
}
