package secp256k1

import (
	"bytes"
	"errors"
	"slices"
	"sync"
)

// Presign consumption lifecycle:
//
//  1. A Presign is generated by a PresignSession and MUST be persisted by the
//     caller immediately after the session completes.
//  2. StartSign constructs and verifies a candidate outbound envelope without
//     making it externally observable.
//  3. StartSign atomically binds the presign to the candidate intent locally,
//     then commits the same immutable intent and envelope through
//     [SignAttemptStore].
//  4. MarshalBinary writes the local claim as a wire-format consumed snapshot.
//     The durable attempt record is the restart and outbox boundary.
//  5. A committed or outcome-unknown attempt can only resume the same intent.

type presignAttemptState uint8

const (
	presignAttemptAvailable presignAttemptState = iota
	presignAttemptSnapshot
	presignAttemptBound
	presignAttemptDiscarded
)

type presignAttemptBinding struct {
	mu     sync.Mutex
	state  presignAttemptState
	intent []byte
}

func newPresignAttemptBinding(consumed bool) *presignAttemptBinding {
	state := presignAttemptAvailable
	if consumed {
		state = presignAttemptSnapshot
	}
	return &presignAttemptBinding{state: state}
}

func (b *presignAttemptBinding) bind(intent []byte, recovered bool) bool {
	if b == nil || len(intent) == 0 {
		return false
	}
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.state == presignAttemptBound {
		return bytes.Equal(b.intent, intent)
	}
	if b.state == presignAttemptDiscarded {
		return false
	}
	if b.state == presignAttemptSnapshot && !recovered {
		return false
	}
	b.state = presignAttemptBound
	b.intent = slices.Clone(intent)
	return true
}

func (b *presignAttemptBinding) discard() {
	if b == nil {
		return
	}
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.state != presignAttemptBound {
		b.state = presignAttemptDiscarded
		b.intent = nil
	}
}

// MarkPresignConsumed marks p's local claim consumed.
// It irreversibly discards an available presign and never releases an existing
// attempt binding. It is not a substitute for [SignAttemptStore].
func MarkPresignConsumed(p *Presign) error {
	if p == nil || p.state == nil {
		return errors.New("nil presign")
	}
	if p.state.consumed == nil {
		return errors.New("presign claim state unavailable")
	}
	if p.state.attempt == nil {
		return errors.New("presign attempt state unavailable")
	}
	p.state.consumed.Store(true)
	p.state.attempt.discard()
	return nil
}

// IsPresignConsumed reports whether the presign has been consumed.
func IsPresignConsumed(p *Presign) bool {
	return p == nil || p.state == nil || p.state.consumed == nil || p.state.attempt == nil || p.state.consumed.Load()
}

func bindPresignToAttempt(presign *Presign, intent []byte, recovered bool) bool {
	if presign == nil || presign.state == nil || presign.state.consumed == nil || presign.state.attempt == nil {
		return false
	}
	if !presign.state.attempt.bind(intent, recovered) {
		return false
	}
	presign.state.consumed.Store(true)
	return true
}
