package secp256k1

import (
	"errors"

	"github.com/islishude/tss"
)

// Presign consumption lifecycle:
//
//  1. A Presign is generated by a PresignSession and MUST be persisted by the
//     caller immediately after the session completes.
//  2. StartSignDigest (or StartSignDigestWithOptions) atomically marks the
//     presign Consumed = true before any outbound signing envelope is emitted.
//     This guarantees that reuse is rejected in-process before any second
//     partial signature can leave the process.
//  3. The caller MUST persist the Consumed flag when storing the presign
//     record. After any call to StartSignDigest, even one that errors partway
//     through, the presign MUST be re-persisted with Consumed = true.
//  4. On process restart, the caller MUST check IsPresignConsumed before
//     calling StartSignDigest. A consumed presign MUST be rejected.
//  5. If the signing session fails after StartSignDigest but the caller is
//     uncertain whether a partial signature was emitted, the presign MUST be
//     discarded rather than reused.
//
// The library refuses to sign with a Consumed presign (see StartSignDigest),
// so as long as the caller persists the Consumed flag, reuse is prevented
// across restarts.

// MarkPresignConsumed returns a copy of p with Consumed set to true.
// Callers should persist the returned copy after a successful signing session
// (or even a failed one where online partials may have been emitted).
func MarkPresignConsumed(p *Presign) (*Presign, error) {
	if p == nil {
		return nil, errors.New("nil presign")
	}
	cp := *p
	cp.Consumed = true
	// Deep-copy variable-length slices so the copy shares no backing storage
	// with the original.
	cp.R = append([]byte(nil), p.R...)
	cp.LittleR = append([]byte(nil), p.LittleR...)
	cp.KShare = append([]byte(nil), p.KShare...)
	cp.ChiShare = append([]byte(nil), p.ChiShare...)
	cp.Delta = append([]byte(nil), p.Delta...)
	cp.TranscriptHash = append([]byte(nil), p.TranscriptHash...)
	cp.Signers = append([]tss.PartyID(nil), p.Signers...)
	return &cp, nil
}

// IsPresignConsumed reports whether the presign has been consumed.
func IsPresignConsumed(p *Presign) bool {
	if p == nil {
		return true // treat nil as consumed
	}
	return p.Consumed
}
