// Code generated by internal/fiat/generate_addchain.go. DO NOT EDIT.

package secp256k1

// fieldInvAddchain computes x^(P-2) mod P via an optimized addition chain.
// Addition chain:
//
//	_10     = 2*1
//	_100    = 2*_10
//	_101    = 1 + _100
//	_111    = _10 + _101
//	_1110   = 2*_111
//	_111000 = _1110 << 2
//	_111111 = _111 + _111000
//	i13     = _111111 << 4 + _1110
//	x12     = i13 << 2 + _111
//	x22     = x12 << 10 + i13 + 1
//	i29     = 2*x22
//	i31     = i29 << 2
//	i54     = i31 << 22 + i31
//	i122    = (i54 << 20 + i29) << 46 + i54
//	x223    = i122 << 110 + i122 + _111
//	i269    = ((x223 << 23 + x22) << 7 + _101) << 3
//	return    _101 + i269
func fieldInvAddchain(x FieldElement) FieldElement {
	var z FieldElement
	var (
		t0 FieldElement
		t1 FieldElement
		t2 FieldElement
		t3 FieldElement
		t4 FieldElement
	)

	t0 = FieldSquare(x)

	z = FieldSquare(t0)

	z = FieldMul(x, z)

	t1 = FieldMul(t0, z)

	t0 = FieldSquare(t1)

	t2 = FieldSquare(t0)
	for s := 1; s < 2; s++ {
		t2 = FieldSquare(t2)
	}

	t2 = FieldMul(t1, t2)

	for s := 0; s < 4; s++ {
		t2 = FieldSquare(t2)
	}

	t0 = FieldMul(t0, t2)

	t2 = FieldSquare(t0)
	for s := 1; s < 2; s++ {
		t2 = FieldSquare(t2)
	}

	t2 = FieldMul(t1, t2)

	for s := 0; s < 10; s++ {
		t2 = FieldSquare(t2)
	}

	t0 = FieldMul(t0, t2)

	t0 = FieldMul(x, t0)

	t3 = FieldSquare(t0)

	t2 = FieldSquare(t3)
	for s := 1; s < 2; s++ {
		t2 = FieldSquare(t2)
	}

	t4 = FieldSquare(t2)
	for s := 1; s < 22; s++ {
		t4 = FieldSquare(t4)
	}

	t2 = FieldMul(t2, t4)

	t4 = FieldSquare(t2)
	for s := 1; s < 20; s++ {
		t4 = FieldSquare(t4)
	}

	t3 = FieldMul(t3, t4)

	for s := 0; s < 46; s++ {
		t3 = FieldSquare(t3)
	}

	t2 = FieldMul(t2, t3)

	t3 = FieldSquare(t2)
	for s := 1; s < 110; s++ {
		t3 = FieldSquare(t3)
	}

	t2 = FieldMul(t2, t3)

	t1 = FieldMul(t1, t2)

	for s := 0; s < 23; s++ {
		t1 = FieldSquare(t1)
	}

	t0 = FieldMul(t0, t1)

	for s := 0; s < 7; s++ {
		t0 = FieldSquare(t0)
	}

	t0 = FieldMul(z, t0)

	for s := 0; s < 3; s++ {
		t0 = FieldSquare(t0)
	}

	z = FieldMul(z, t0)

	return z
}

// fieldSqrtAddchain computes x^((P+1)/4) mod P via an optimized addition chain.
// Addition chain:
//
//	_10      = 2*1
//	_11      = 1 + _10
//	_1100    = _11 << 2
//	_1111    = _11 + _1100
//	_11110   = 2*_1111
//	_11111   = 1 + _11110
//	_1111100 = _11111 << 2
//	_1111111 = _11 + _1111100
//	x11      = _1111111 << 4 + _1111
//	x22      = x11 << 11 + x11
//	x27      = x22 << 5 + _11111
//	x54      = x27 << 27 + x27
//	x108     = x54 << 54 + x54
//	x216     = x108 << 108 + x108
//	x223     = x216 << 7 + _1111111
//	return     ((x223 << 23 + x22) << 6 + _11) << 2
func fieldSqrtAddchain(x FieldElement) FieldElement {
	var z FieldElement
	var (
		t0 FieldElement
		t1 FieldElement
		t2 FieldElement
		t3 FieldElement
	)

	z = FieldSquare(x)

	z = FieldMul(x, z)

	t0 = FieldSquare(z)
	for s := 1; s < 2; s++ {
		t0 = FieldSquare(t0)
	}

	t0 = FieldMul(z, t0)

	t1 = FieldSquare(t0)

	t2 = FieldMul(x, t1)

	t1 = FieldSquare(t2)
	for s := 1; s < 2; s++ {
		t1 = FieldSquare(t1)
	}

	t1 = FieldMul(z, t1)

	t3 = FieldSquare(t1)
	for s := 1; s < 4; s++ {
		t3 = FieldSquare(t3)
	}

	t0 = FieldMul(t0, t3)

	t3 = FieldSquare(t0)
	for s := 1; s < 11; s++ {
		t3 = FieldSquare(t3)
	}

	t0 = FieldMul(t0, t3)

	t3 = FieldSquare(t0)
	for s := 1; s < 5; s++ {
		t3 = FieldSquare(t3)
	}

	t2 = FieldMul(t2, t3)

	t3 = FieldSquare(t2)
	for s := 1; s < 27; s++ {
		t3 = FieldSquare(t3)
	}

	t2 = FieldMul(t2, t3)

	t3 = FieldSquare(t2)
	for s := 1; s < 54; s++ {
		t3 = FieldSquare(t3)
	}

	t2 = FieldMul(t2, t3)

	t3 = FieldSquare(t2)
	for s := 1; s < 108; s++ {
		t3 = FieldSquare(t3)
	}

	t2 = FieldMul(t2, t3)

	for s := 0; s < 7; s++ {
		t2 = FieldSquare(t2)
	}

	t1 = FieldMul(t1, t2)

	for s := 0; s < 23; s++ {
		t1 = FieldSquare(t1)
	}

	t0 = FieldMul(t0, t1)

	for s := 0; s < 6; s++ {
		t0 = FieldSquare(t0)
	}

	z = FieldMul(z, t0)

	for s := 0; s < 2; s++ {
		z = FieldSquare(z)
	}

	return z
}
