// Code generated by internal/fiat/generate_addchain.go. DO NOT EDIT.

package secp256k1

// scalarInvAddchain computes x^(N-2) mod N via an optimized addition chain.
// Addition chain:
//
//	_10       = 2*1
//	_11       = 1 + _10
//	_101      = _10 + _11
//	_111      = _10 + _101
//	_1001     = _10 + _111
//	_1011     = _10 + _1001
//	_1101     = _10 + _1011
//	_110100   = _1101 << 2
//	_111111   = _1011 + _110100
//	_1111110  = 2*_111111
//	_1111111  = 1 + _1111110
//	_11111110 = 2*_1111111
//	_11111111 = 1 + _11111110
//	i17       = _11111111 << 3
//	i19       = i17 << 2
//	i20       = 2*i19
//	i21       = 2*i20
//	i39       = (i21 << 7 + i20) << 9 + i21
//	i73       = (i39 << 6 + i19) << 26 + i39
//	x127      = (i73 << 4 + i17) << 60 + i73 + _1111111
//	i154      = ((x127 << 5 + _1011) << 3 + _101) << 4
//	i166      = ((_101 + i154) << 4 + _111) << 5 + _1101
//	i181      = ((i166 << 2 + _11) << 5 + _111) << 6
//	i193      = ((_1101 + i181) << 5 + _1011) << 4 + _1101
//	i214      = ((i193 << 3 + 1) << 6 + _101) << 10
//	i230      = ((_111 + i214) << 4 + _111) << 9 + _11111111
//	i247      = ((i230 << 5 + _1001) << 6 + _1011) << 4
//	i261      = ((_1101 + i247) << 5 + _11) << 6 + _1101
//	i283      = ((i261 << 10 + _1101) << 4 + _1001) << 6
//	return      (1 + i283) << 8 + _111111
func scalarInvAddchain(x Scalar) Scalar {
	var z Scalar
	var (
		t0  Scalar
		t1  Scalar
		t2  Scalar
		t3  Scalar
		t4  Scalar
		t5  Scalar
		t6  Scalar
		t7  Scalar
		t8  Scalar
		t9  Scalar
		t10 Scalar
		t11 Scalar
		t12 Scalar
	)

	z = ScalarSquare(x)

	t2 = ScalarMul(x, z)

	t6 = ScalarMul(z, t2)

	t5 = ScalarMul(z, t6)

	t0 = ScalarMul(z, t5)

	t3 = ScalarMul(z, t0)

	t1 = ScalarMul(z, t3)

	z = ScalarSquare(t1)
	for s := 1; s < 2; s++ {
		z = ScalarSquare(z)
	}

	z = ScalarMul(t3, z)

	t4 = ScalarSquare(z)

	t7 = ScalarMul(x, t4)

	t4 = ScalarSquare(t7)

	t4 = ScalarMul(x, t4)

	t9 = ScalarSquare(t4)
	for s := 1; s < 3; s++ {
		t9 = ScalarSquare(t9)
	}

	t10 = ScalarSquare(t9)
	for s := 1; s < 2; s++ {
		t10 = ScalarSquare(t10)
	}

	t11 = ScalarSquare(t10)

	t8 = ScalarSquare(t11)

	t12 = ScalarSquare(t8)
	for s := 1; s < 7; s++ {
		t12 = ScalarSquare(t12)
	}

	t11 = ScalarMul(t11, t12)

	for s := 0; s < 9; s++ {
		t11 = ScalarSquare(t11)
	}

	t8 = ScalarMul(t8, t11)

	t11 = ScalarSquare(t8)
	for s := 1; s < 6; s++ {
		t11 = ScalarSquare(t11)
	}

	t10 = ScalarMul(t10, t11)

	for s := 0; s < 26; s++ {
		t10 = ScalarSquare(t10)
	}

	t8 = ScalarMul(t8, t10)

	t10 = ScalarSquare(t8)
	for s := 1; s < 4; s++ {
		t10 = ScalarSquare(t10)
	}

	t9 = ScalarMul(t9, t10)

	for s := 0; s < 60; s++ {
		t9 = ScalarSquare(t9)
	}

	t8 = ScalarMul(t8, t9)

	t7 = ScalarMul(t7, t8)

	for s := 0; s < 5; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t3, t7)

	for s := 0; s < 3; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t6, t7)

	for s := 0; s < 4; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t6, t7)

	for s := 0; s < 4; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t5, t7)

	for s := 0; s < 5; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t1, t7)

	for s := 0; s < 2; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t2, t7)

	for s := 0; s < 5; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t5, t7)

	for s := 0; s < 6; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t1, t7)

	for s := 0; s < 5; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t3, t7)

	for s := 0; s < 4; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(t1, t7)

	for s := 0; s < 3; s++ {
		t7 = ScalarSquare(t7)
	}

	t7 = ScalarMul(x, t7)

	for s := 0; s < 6; s++ {
		t7 = ScalarSquare(t7)
	}

	t6 = ScalarMul(t6, t7)

	for s := 0; s < 10; s++ {
		t6 = ScalarSquare(t6)
	}

	t6 = ScalarMul(t5, t6)

	for s := 0; s < 4; s++ {
		t6 = ScalarSquare(t6)
	}

	t5 = ScalarMul(t5, t6)

	for s := 0; s < 9; s++ {
		t5 = ScalarSquare(t5)
	}

	t4 = ScalarMul(t4, t5)

	for s := 0; s < 5; s++ {
		t4 = ScalarSquare(t4)
	}

	t4 = ScalarMul(t0, t4)

	for s := 0; s < 6; s++ {
		t4 = ScalarSquare(t4)
	}

	t3 = ScalarMul(t3, t4)

	for s := 0; s < 4; s++ {
		t3 = ScalarSquare(t3)
	}

	t3 = ScalarMul(t1, t3)

	for s := 0; s < 5; s++ {
		t3 = ScalarSquare(t3)
	}

	t2 = ScalarMul(t2, t3)

	for s := 0; s < 6; s++ {
		t2 = ScalarSquare(t2)
	}

	t2 = ScalarMul(t1, t2)

	for s := 0; s < 10; s++ {
		t2 = ScalarSquare(t2)
	}

	t1 = ScalarMul(t1, t2)

	for s := 0; s < 4; s++ {
		t1 = ScalarSquare(t1)
	}

	t0 = ScalarMul(t0, t1)

	for s := 0; s < 6; s++ {
		t0 = ScalarSquare(t0)
	}

	t0 = ScalarMul(x, t0)

	for s := 0; s < 8; s++ {
		t0 = ScalarSquare(t0)
	}

	z = ScalarMul(z, t0)

	return z
}
