package main

var manifest = []target{
	{
		Name:     "wire/envelope",
		Kind:     "wire",
		Tier:     "0",
		Packages: []string{"."},
		Update:   runSpec{Run: "^TestGoldenEnvelope$", Env: map[string]string{"UPDATE_GOLDEN": "1"}},
		Verify:   runSpec{Run: "^TestGoldenEnvelope$"},
		Outputs: []string{
			"wire/v1/envelope/Envelope.golden",
		},
	},
	{
		Name:     "wire/tss",
		Kind:     "wire",
		Tier:     "0",
		Packages: []string{"."},
		Update:   runSpec{Run: "^TestGolden(BlameEvidence|IdentificationRecord|SigningContext|BroadcastAck|BroadcastCertificate)$", Env: map[string]string{"UPDATE_GOLDEN": "1"}},
		Verify:   runSpec{Run: "^TestGolden(BlameEvidence|IdentificationRecord|SigningContext|BroadcastAck|BroadcastCertificate)$"},
		Outputs: []string{
			"wire/v1/tss/BlameEvidence.golden",
			"wire/v1/tss/IdentificationRecord.golden",
			"wire/v1/tss/SigningContext.golden",
			"wire/v1/tss/BroadcastAck.golden",
			"wire/v1/tss/BroadcastCertificate.golden",
		},
	},
	{
		Name:     "wire/frost",
		Kind:     "wire",
		Tier:     "0",
		Packages: []string{"./frost/ed25519"},
		Update:   runSpec{Run: "^TestGolden", Env: map[string]string{"UPDATE_GOLDEN": "1"}},
		Verify:   runSpec{Run: "^TestGolden"},
		Secret:   true,
		Outputs: []string{
			"wire/v1/frost/KeyShare.golden",
			"wire/v1/frost/VerificationShare.golden",
			"wire/v1/frost/KeygenCommitmentsPayload.golden",
			"wire/v1/frost/KeygenSharePayload.golden",
			"wire/v1/frost/NonceCommitmentPayload.golden",
			"wire/v1/frost/SignPartialPayload.golden",
			"wire/v1/frost/KeygenConfirmation.golden",
			"wire/v1/frost/ReshareCommitmentsPayload.golden",
			"wire/v1/frost/ReshareSharePayload.golden",
			"wire/v1/frost/TrustedDealerImportPlan.golden",
			"wire/v1/frost/TrustedDealerContribution.golden",
		},
	},
	{
		Name:     "wire/zk",
		Kind:     "wire",
		Tier:     "0/1",
		Packages: []string{"./internal/zk/paillier", "./internal/zk/schnorr", "./internal/zk/schnorred25519"},
		Update:   runSpec{Run: "^TestGolden", Env: map[string]string{"UPDATE_GOLDEN": "1"}},
		Verify:   runSpec{Run: "^TestGolden"},
		Outputs: []string{
			"wire/v1/zk/SecurityParams.golden",
			"wire/v1/zk/ModulusProof.golden",
			"wire/v1/zk/FactorProof.golden",
			"wire/v1/zk/RingPedersenParams.golden",
			"wire/v1/zk/RingPedersenProof.golden",
			"wire/v1/zk/EncProof.golden",
			"wire/v1/zk/AffGProof.golden",
			"wire/v1/zk/LogStarProof.golden",
			"wire/v1/zk/SchnorrProof.golden",
			"wire/v1/zk/Ed25519SchnorrProof.golden",
		},
	},
	{
		Name:     "wire/cggmp21-fast",
		Kind:     "wire",
		Tier:     "0",
		Packages: []string{"./cggmp21/secp256k1"},
		Update:   runSpec{Run: "^(TestFast_Golden|TestGoldenResharePlanMarshalBinary)", Env: map[string]string{"UPDATE_GOLDEN": "1"}},
		Verify:   runSpec{Run: "^(TestFast_Golden|TestGoldenResharePlanMarshalBinary)"},
		Secret:   true,
		Outputs: []string{
			"wire/v1/cggmp21/Presign.fast.golden",
			"wire/v1/cggmp21/VerificationShare.golden",
			"wire/v1/cggmp21/PaillierPublicShare.golden",
			"wire/v1/cggmp21/RingPedersenPublicShare.golden",
			"wire/v1/cggmp21/Figure6CommitmentPayload.golden",
			"wire/v1/cggmp21/AuxInfoCommitmentPayload.golden",
			"wire/v1/cggmp21/KeygenConfirmation.golden",
			"wire/v1/cggmp21/SignPartialPayload.golden",
			"wire/v1/cggmp21/PresignRound3Payload.golden",
			"wire/v1/cggmp21/ResharePlan.golden",
			"wire/v1/cggmp21/TrustedDealerImportPlan.golden",
			"wire/v1/cggmp21/TrustedDealerContribution.golden",
		},
	},
	{
		Name:     "wire/cggmp21-integration",
		Kind:     "wire",
		Tier:     "2",
		Packages: []string{"./cggmp21/secp256k1"},
		Update:   runSpec{Run: "^TestGoldenCGGMP21(KeyShare|Presign)$", Tags: []string{"integration"}, Env: map[string]string{"UPDATE_GOLDEN": "1"}},
		Verify:   runSpec{Run: "^TestGoldenCGGMP21(KeyShare|Presign)$", Tags: []string{"integration"}},
		Secret:   true,
		Outputs: []string{
			"wire/v1/cggmp21/KeyShare.golden",
			"wire/v1/cggmp21/Presign.golden",
		},
	},
	{
		Name:        "protocol/ed25519-bip32",
		Kind:        "protocol",
		Tier:        "0",
		Packages:    []string{"./internal/bip32util"},
		Verify:      runSpec{Run: "^TestDeriveEd25519KhovratovichLawIndependentPublicVectors$"},
		Description: "verify-only independent public vectors; no update target",
		Outputs: []string{
			"protocol/ed25519-bip32/khovratovich_law_vectors.json",
		},
	},
	{
		Name:     "protocol/frost-ed25519",
		Kind:     "protocol",
		Tier:     "0",
		Packages: []string{"./frost/ed25519"},
		Update:   runSpec{Run: "^TestGenerateVectors$", Tags: []string{"vectorgen"}},
		Verify:   runSpec{Run: "^TestFROSTProtocolFormatRegressionVectors$"},
		Outputs: []string{
			"protocol/frost-ed25519/frost_ed25519_vectors.json",
		},
	},
	{
		Name:        "protocol/cggmp21-secp256k1",
		Kind:        "protocol",
		Tier:        "2",
		Packages:    []string{"./cggmp21/secp256k1"},
		Update:      runSpec{Run: "^TestGenerateVectors$", Tags: []string{"vectorgen"}},
		Verify:      runSpec{Run: "CrossImplementation", Tags: []string{"integration"}},
		Description: "non-deterministic generation",
		Outputs: []string{
			"protocol/cggmp21-secp256k1/cggmp21_secp256k1_vectors.json",
		},
	},
	{
		Name:        "fixtures/cggmp21-keygen",
		Kind:        "fixtures",
		Tier:        "2",
		Packages:    []string{"./cggmp21/secp256k1"},
		Update:      runSpec{Run: "^TestGenerateKeygenFixtures$", Tags: []string{"vectorgen"}},
		Verify:      runSpec{Run: "^(TestCommittedKeygenFixturesCoverCachedCombinations|TestKeygenFixtureCanonicalRoundTrip|TestCachedKeygenSharesReturnsIndependentClones)$"},
		Secret:      true,
		Description: "committed test-only private shares",
		Outputs: []string{
			"fixtures/cggmp21-secp256k1/keygen_fixtures.json",
		},
	},
}
